added check for existence of openssl binary

diff --git a/cipherscan b/cipherscan
--- a/cipherscan
+++ b/cipherscan
@@ -7,7 +7,7 @@
 
 DOBENCHMARK=0
 BENCHMARKITER=30
-OPENSSLBIN="/usr/local/bin/openssl/openssl"
+OPENSSLBIN="/usr/local/bin/openssl/apps/openssl"
 CACERTS=${CACERTS:-/etc/pki/tls/certs/ca-bundle.crt}
 if [ ! -e "$CACERTS" ]; then
     echo "Warning: CA Certificates not found at $CACERTS, export CACERTS variable with location of your trust anchors" 1>&2
@@ -323,6 +323,11 @@ do
             ;;
     esac
 done
+
+if [[ ! -e $OPENSSLBIN ]]; then
+    echo "error: could not find ${OPENSSLBIN}" >&2
+    exit 1
+fi
 
 if [ $VERBOSE != 0 ] ; then
     echo "Loading $($OPENSSLBIN ciphers -v $CIPHERSUITE 2>/dev/null|grep Kx|wc -l) ciphersuites from $(echo -n $($OPENSSLBIN version 2>/dev/null))"
